Updated
dom96/binary_size pull request #14
Opened 2020-11-22 12:53 UTC by Pernat1y

Added C binary
Specified versions of compiles
Added test with stripped binaries

Everything, except of crystal, was tested on Fedora 33. Crystal was on Kali Linux.

2020-11-22 19:21 UTC, dom96 commented
Hmm, curious why Nim has bloated so much. Can you repro the sizes I've had with older Nim version?

2020-11-22 20:48 UTC, Pernat1y commented
Have you used 'strip' on binaries in original tests? The test results are closer to those values.

2020-11-22 21:16 UTC, Pernat1y commented
So, we got
88840   (72544 stripped) with Nim 1.4.0 from official site, and
409936 (47400 stripped) with Nim 1.4.0 from Fedora's repository.

Seems like there is some difference in provided configuration files.

Also, comparison with older versions (binaries installed from archives from the website, unstripped):
Nim 1.0.0 - 84048
Nim 1.0.10 - 84048
Nim 1.2.0 - 88592
Nim 1.2.8 - 88592
Nim 1.4.0 - 88840

2021-01-12 13:20 UTC, Pernat1y commented
Updated Rust, Nim and Go
Added Free Pascal and NASM

2021-01-12 13:33 UTC, Pernat1y commented
Updated Rust, Nim and Go
Added V, Free Pascal and NASM

2021-01-12 16:29 UTC, dom96 requested changes

2021-01-12 16:29 UTC, dom96 commented on hello.v
> +}
That's interesting. Seems V conflicts with another programming language: http://rosettacode.org/wiki/Hello_world/Text#V. I use Rosetta Code as a source of truth here so I cannot accept this language.

2021-01-13 11:39 UTC, Pernat1y commented on hello.v
> +}
http://rosettacode.org/wiki/Hello_world/Text#Vlang

2021-01-13 22:07 UTC, merged